name: Auto-merge Dependabot PRs

on:
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'success'
    steps:
      - name: Merge Dependabot PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = context.payload.check_suite.pull_requests || [];
            for (const ref of prs) {
              // 1) Fetch full PR data
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ref.number
              });

              // 2) Only Dependabot PRs
              if (pr.user?.login !== 'dependabot[bot]') continue;

              // 3) Ensure all status checks on this SHA are green
              const { data: statuses } = await github.rest.repos.listCommitStatusesForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: pr.head.sha
              });
              if (statuses.some(s => s.state !== 'success')) continue;

              // 4) Merge with squash
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
            }
